project:
  type: website
  output-dir: docs


website:
  #title: Bulettin Mensuel de la Vaccination
  favicon: /static/img/who-emblem.png
  #site-url: https://benguimbis.github.io/registration_website/
  cookie-consent: true
  #repo-url: https://github.com/benguimbis/registration_website
  repo-actions: [source, issue]

  navbar:
    logo: /img/static/logo-en.svg
    background: light
    foreground: dark
    right:
      - text: Tutoriel
        href: index.qmd
        icon: bi-house-door-fill
      - text: "Outil d'ajustement"
        href: pop_calculator.qmd



  page-footer:
    left: |
      {{< fa regular copyright >}} WHO-IST CA 2024<br>
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org)
    right:
      - text: <img src = "img/static/logo-en.svg"  alt = "WHO-AFRO" width = "250" height = "62.5">&nbsp;
        href: https://www.afro.who.int/
        aria-label: WHO-AFRO





format:
  html:
    theme: dinty.scss
    css: styles.css
    highlight-style: kate
    code-block-bg: true
    code-block-border-left: "#78c2ad"
    code-fold: true
    code-tools: false
    fig-width: 12
    fig-height: 10
    fig-dpi: 700
    fig-format: svg
    lang: fr
    fig-align: center
    keep-md: false



execute:
  freeze: auto
  echo: false
  warning: false
  error: false


knitr:
  opts_chunk:
    fig.path: figures/

crossref:
  chapters: true
  tbl-title: Tableau

language:
  en:
    crossref-fig-title: "figure"
    crossref-tbl-title: "table"
  fr:
    crossref-fig-title: "figure"
    crossref-tbl-title: "tableau"

lightbox: true
